language: elixir

elixir:
  - 1.5.1
otp_release:
  - 20.0
services:
  - postgresql
before_script:
  - cp apps/montreal_elixir/config/travis.exs apps/montreal_elixir/config/test.exs
  - mix do ecto.create, ecto.migrate
script:
  - mix project.check
